- name: install puppet-agent

  hosts: Test

  become: yes

  tasks:

    - name: run apt-get update

      apt:

              # update_cache: yes

    - name: install puppet-agent

      apt:

        name: puppet-agent

        state: present

    - name: start service

      systemd:

        name: puppet

        state: restarted
